package ua.com.foxminded.yuriy.carrestservice.properties;

public class SwaggerDescription {  
  public static final String MODEL_GET_ALL_DESCRIPTION = "Get entire list of Models.\n\n Parameters (OPTIONAL) :\n - **page** : Page of pagination, **default value = 0**, example = 10.\n - **size** : Size of the page for pagination, **default value = 20**, example = 10\n - **sort** : Sorting criteria in the format : property **{id // name // brand}** , asc | desc. **Default is UNSORTED**. Multiple sort criteria are supported, **example = name,asc.**";
  public static final String BRAND_GET_ALL_DESCRIPTION = "Get entire list of Models.\n\n Parameters (OPTIONAL) :\n - **page** : Page of pagination, **default value = 0**, example = 10.\n - **size** : Size of the page for pagination, **default value = 20**, example = 10\n - **sort** : Sorting criteria in the format : property **{id // name // models}** , asc|desc. **Default is UNSORTED**. Multiple sort criteria are supported, **example = name,asc.**";
  public static final String CATEGORY_GET_ALL_DESCRIPTION = "Get entire list of Models.\n\n Parameters (OPTIONAL) :\n - **page** : Page of pagination, **default value = 0**, example = 10.\n - **size** : Size of the page for pagination, **default value = 20**, example = 10\n - **sort** : Sorting criteria in the format : property **{id // name}** , asc|desc. **Default is UNSORTED**. Multiple sort criteria are supported, **example = name,asc.**";
  public static final String CAR_GET_ALL_DESCRIPTION = "Retrieve a list of models with various filter and sort options.\n\n Parameters (OPTIONAL):\n - **page** : Page number for pagination (default: 0), **example: 5.**\n - **size** : Page size for pagination (default: 10), **example: 10**\n - **sortOrder** : Sorting order, 'asc' or 'desc' (default: asc), **example: asc**.\n - **sortBy** : Property to sort by **[CASE SENSITIVE : id // objectId // brand // model // productionYear]** (default : model), **example: objectId**.\n - **brand** : Filter by brand name, **example: Audi. Or more than one, example : Audi,BMW**\n - **category** : Filter by category, **example: SUV. Or more than one, example : Sedan,SUV**\n - **model** : Filter by model name, **example: Q3. Or more than one, example : Q3,X3**\n - **year** : Filter by production year. Options :\n  1) **Between** two years **[y0,y1]** (e.g., 2000, 2020)\n  2) **After** a specific year **[y0]** (e.g., 2015)\n  3) **Before** a specific year **[0, y1]** (e.g., 0, 2015), example: 0,2020.";
  public static final String CAR_GET_ALL_EXAMPLE_ONE = "{ \"page\": 5, \"size\": 10, \"sortOrder\": \"asc\", \"sortBy\": \"objectId\", \"brand\": [\"Audi\", \"BMW\"], \"category\": [\"Sedan\", \"SUV\"], \"model\": [\"Q3\", \"X3\"], \"year\": [2000] }";
  }
