#Source
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url = ${DB_URL}
spring.datasource.username = ${DB_USERNAME}
spring.datasource.password = ${DB_PASSWORD}
#Flyway
spring.flyway.enabled = true
spring.flyway.baseline-on-migrate = true
spring.flyway.clean-disabled = false
#Hibernate
spring.jpa.show-sql = false
spring.jpa.hibernate.ddl-auto = update
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
#Sorting **default Values
sortOrder: asc
sortBy: model
pageSize: 10
page: 0
dataFile: src/main/resources/static/file.csv
#oauth2
auth0.audience = ${AUDIENCE_CAR_SERVICE_ADMIN}
spring.security.oauth2.resourceserver.jwt.issuer-uri = ${URI_CAR_SERVICE_ADMIN}
#swagger
springdoc.swagger-ui.path=/api-doc
#
descriptionModelGetAllMethod: "Get entire list of Models.\n\n Parameters (OPTIONAL) :\n - **page** : Page of pagination, **default value = 0**, example = 10.\n - **size** : Size of the page for pagination, **default value = 20**, example = 10\n - **sort** : Sorting criteria in the format : property **{id // name // brand}** , asc | desc. **Default is UNSORTED**. Multiple sort criteria are supported, **example = name,asc.**"
descriptionBrandGetAllMethod: "Get entire list of Models.\n\n Parameters (OPTIONAL) :\n - **page** : Page of pagination, **default value = 0**, example = 10.\n - **size** : Size of the page for pagination, **default value = 20**, example = 10\n - **sort** : Sorting criteria in the format : property **{id // name // models}** , asc|desc. **Default is UNSORTED**. Multiple sort criteria are supported, **example = name,asc.**"
descriptionCategoryGetAllMethod: "Get entire list of Models.\n\n Parameters (OPTIONAL) :\n - **page** : Page of pagination, **default value = 0**, example = 10.\n - **size** : Size of the page for pagination, **default value = 20**, example = 10\n - **sort** : Sorting criteria in the format : property **{id // name}** , asc|desc. **Default is UNSORTED**. Multiple sort criteria are supported, **example = name,asc.**"
descriptionCarGetAllMethod: "Retrieve a list of models with various filter and sort options.\n\n Parameters (OPTIONAL):\n - **page** : Page number for pagination (default: 0), **example: 5.**\n - **size** : Page size for pagination (default: 10), **example: 10**\n - **sortOrder** : Sorting order, 'asc' or 'desc' (default: asc), **example: asc**.\n - **sortBy** : Property to sort by **[CASE SENSITIVE : id // objectId // brand // model // productionYear]** (default : model), **example: objectId**.\n - **brand** : Filter by brand name, **example: Audi. Or more than one, example : Audi,BMW**\n - **category** : Filter by category, **example: SUV. Or more than one, example : Sedan,SUV**\n - **model** : Filter by model name, **example: Q3. Or more than one, example : Q3,X3**\n - **year** : Filter by production year. Options :\n  1) **Between** two years **[y0,y1]** (e.g., 2000, 2020)\n  2) **After** a specific year **[y0]** (e.g., 2015)\n  3) **Before** a specific year **[0, y1]** (e.g., 0, 2015), example: 0,2020."
